import { useSearchParams, Link } from "react-router";
import { AlertCircle } from "lucide-react";
import { Card, CardContent } from "../components/ui/card";
import { Button } from "../components/ui/button";

/**
 * Catches legacy QR URLs that used the old `/verify.html?v=<id>` format
 * (pre-Phase 11). Those URLs don't carry enough information (donor_id,
 * patient_id, token) for the new verification flow, so we can't auto-forward
 * them. Instead we render a clear "please regenerate the QR" page.
 *
 * Registered as `/verify.html` AND `/verify` in routes.tsx.
 */
const VerifyLegacyRedirect = () => {
  const [params] = useSearchParams();
  const legacyId = params.get("v") || params.get("id") || params.get("request") || "";

  return (
    <div className="min-h-screen bg-slate-50 flex items-center justify-center p-4">
      <Card className="max-w-md w-full shadow-lg border-t-4 border-t-amber-500">
        <CardContent className="pt-8 text-center space-y-4">
          <AlertCircle className="h-16 w-16 text-amber-500 mx-auto mb-2" />
          <h2 className="text-2xl font-bold text-slate-900">Outdated QR Code</h2>
          <p className="text-slate-600">
            This QR was generated by an older version of the system and is
            missing the secure token needed for verification.
          </p>
          {legacyId ? (
            <p className="text-xs text-slate-400">
              Legacy reference: <span className="font-mono">{legacyId}</span>
            </p>
          ) : null}
          <div className="bg-amber-50 border border-amber-200 rounded-lg p-4 text-left text-sm text-amber-900">
            <p className="font-semibold mb-1">What to do:</p>
            <ol className="list-decimal list-inside space-y-1">
              <li>Ask the donor to open their dashboard.</li>
              <li>
                Tap <span className="font-semibold">"Show QR"</span> on the matched request.
              </li>
              <li>A fresh QR with a secure token will appear — scan that one.</li>
            </ol>
          </div>
          <Button asChild className="w-full bg-red-600 hover:bg-red-700">
            <Link to="/">Back to Home</Link>
          </Button>
        </CardContent>
      </Card>
    </div>
  );
};

export default VerifyLegacyRedirect;
